<?php
/**
 * Handler for iTunes RSS feeds.
 * @todo: comment this file
 * @todo: implement podcast categoy
 */

/**
 * Implements hook_menu().
 */
function swift_itunes_rss_menu() {

  $items['show/%/feed'] = array(
    'title' => 'Test',
    'page callback' => 'swift_itunes_rss_feed',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;

}


function swift_itunes_rss_feed($path) {

  $nid = drupal_lookup_path('source', 'show/'.$path);
  $node = menu_get_object("node", 1, $nid);

  if(!$node) {
    drupal_not_found();
  }

  $result = db_select('field_data_field_show', 's')
             ->fields('s')
             ->condition('field_show_nid', $node->nid,'=')
             ->orderBy('entity_id', 'DESC')
             ->execute();
  $rec = '';

  while($record = $result->fetchAssoc()) {

    $rec .= $record['entity_id'].',';
  }

  if(!isset($rec)) {
    drupal_not_found();
  }

  $rec = substr($rec,'0','-1');
  $rec = explode(',',$rec);

  $podcasts = node_load_multiple($rec);

  //prepare output
  $output = '<?xml version="1.0" encoding="UTF-8"?>';
  $output .= '<rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" version="2.0">';
    $output .= '<channel>';
      $output .= '<title>'.$node->title.'</title>';
      $output .= '<link>http://chipbit.net/show/'.$path.'</link>';
      $output .= '<description>'.strip_tags($node->body['und']['0']['safe_value']).'</description>';
      $output .= '<language>en-us</language>';
      $output .= '<itunes:image href="'.file_create_url($node->field_logo['und']['0']['uri']).'" />';
      $output .= '<itunes:category text="Video-Games" />';
      $output .= '<itunes:author>ChipBit</itunes:author>';
      $output .= '<itunes:owner>ChipBit Radio</itunes:owner>';

      //process podcast items
      foreach($podcasts as $podcast) {

        if(isset($podcast->field_file['und']['0']['uri'])) {
          $file = file_create_url($podcast->field_file['und']['0']['uri']);
        }
        $date = date('D, j M Y H:i:s T',$podcast->field_air_date['und']['0']['value']);
        if(isset($podcast->field_duration['und']['0']['value'])) {
          $duration = gmdate('H:i:s', $podcast->field_duration['und']['0']['value']);
        } else {
          $duration = '01:00:00';
        }

        $output .= '<item>';
          $output .= '<title>#'.$podcast->field_episode_number['und']['0']['value'].' - '.$podcast->title.'</title>';
          $output .= '<description>'.strip_tags($podcast->body['und']['0']['safe_value']).'</description>';
          $output .= '<guid>'.$file.'</guid>';
          $output .= '<enclosure url="'.$file.'" type="audio/mpeg" length="1"/>';
          $output .= '<pubDate>'.$date.'</pubDate>';
          $output .= '<itunes:duration>'.$duration.'</itunes:duration>';
        $output .= '</item>';
      }

    $output .= '</channel>';
  $output .= '</rss>';

  header('Content-Type: text/xml');
  print $output;
}
